-- CreateEnum
CREATE TYPE "Tag" AS ENUM ('ELECTRONICS', 'CLOTHING', 'FURNITURE', 'BOOKS', 'SPORTS', 'TOYS', 'VEHICLES', 'ART', 'MUSIC', 'APPLIANCES', 'JEWELRY', 'COLLECTIBLES', 'GARDEN', 'PETS', 'HEALTH', 'BEAUTY', 'FOOD', 'HANDMADE', 'GAMING', 'OFFICE', 'OUTDOORS', 'HOME_DECOR', 'BABY', 'INDUSTRIAL', 'OTHER');

-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "tags" "Tag"[];
